# Generated by Django 6.0.1 on 2026-01-29 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='fas fa-box', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название экспоната')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('catalog_number', models.CharField(blank=True, max_length=100, verbose_name='Каталожный номер')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Штрих-код')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Ключевые слова (теги, через запятую)')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('acquisition_source', models.CharField(blank=True, max_length=300, verbose_name='Источник поступления')),
                ('creation_date', models.CharField(blank=True, max_length=100, verbose_name='Дата создания (оригинала)')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор/Изготовитель')),
                ('historical_context', models.TextField(blank=True, verbose_name='Исторический контекст')),
                ('condition', models.TextField(blank=True, verbose_name='Состояние сохранности')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Место хранения')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размеры (ШхВхГ)')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оценочная стоимость')),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Страховая стоимость')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве'), ('repair', 'На реставрации')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exhibits', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_exhibits', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен')),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
                'ordering': ['-created_at'],
                'permissions': [('can_publish', 'Может публиковать экспонаты'), ('can_archive', 'Может отправлять в архив')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='exhibit_docs/%Y/%m/%d/', verbose_name='Файл документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('scan', 'Скан документа'), ('certificate', 'Сертификат подлинности'), ('manual', 'Инструкция/Руководство'), ('research', 'Научное исследование'), ('act', 'Акт приема-передачи'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружен')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='museum.exhibit')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Изменен'), ('published', 'Опубликован'), ('archived', 'Архивирован'), ('restored', 'Восстановлен'), ('photo_added', 'Добавлено фото'), ('document_added', 'Добавлен документ'), ('status_changed', 'Изменен статус')], max_length=20, verbose_name='Действие')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменено')),
                ('description', models.TextField(blank=True, verbose_name='Описание изменения')),
                ('changed_fields', models.JSONField(blank=True, default=dict, verbose_name='Измененные поля')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='museum.exhibit')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='exhibit_photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название фотографии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='museum.exhibit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружено')),
            ],
            options={
                'verbose_name': 'Фотография экспоната',
                'verbose_name_plural': 'Фотографии экспонатов',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
